name: todo
description: To-Do list

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: '^0.8.2+3'
  firebase_storage: '^1.0.4'
  image_picker: '^0.4.10'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/notebook.jpg

  fonts:
    - family: Raleway
      fonts:
        - asset: third_party/Raleway-Regular.ttf
